### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by joshsmith** [bendrucker/snakecase-keys#21]
Hey @bendrucker, thank you for making this package and maintaining it. Not enough thanks is actually given in open source, so just wanted to especially emphasize that.

I was wondering if you would consider adding some release notes alongside your major version changes. For example, I see that the major version change to `3.x` was a result of changing the version of `node` you support. It would make things easier for those who rely on this library as a dependency to see this in the notes, vs trying to figure out whether there are breaking changes from the individual commits.

I believe there are a number of packages that can make doing this less of a chore whenever you publish an update. If you need some recommendations, I'd be happy to provide them.

Thanks again for your work here!

**Comment by bendrucker** [comment]
My position in the past has been “no” to release notes/changelogs in small modules because I don’t feel confident that I’d maintain them properly. If you want to send a PR that creates attaches them to GitHub releases automatically I’m up for that.

I don’t plan to work invest time into implementing this myself but if you can take it through to a PR I’m happy to review and adopt.

**Comment by joshsmith** [comment]
No worries at all. And I understand the hesitation. I'd probably feel the same, especially since I'm a horrible maintainer. I'm going to just close this in that case, if that's alright with you!

**Comment by rdsedmundo** [comment]
Came here for the same purpose, but now with v5.0.0. I have no idea what has been changed in the latest major version and have to literally look through commits to see if there's anything that affects me.

> “no” to release notes/changelogs in small modules

I'm sorry, but this makes no sense at all. If anything, those are the most important modules to have release notes, because a lot of the bigger modules depend on them and could break.
