### ISSUE TITLE
Cannot use import from TS

### ISSUE THREAD

**Issue by alexmantaut** [bendrucker/snakecase-keys#44]
Hi,

I am trying to use the library from TS. When I include the library using require as per your example it works ok, but when I try to include it using an import, it does not work...

I tried:
const snakeCaseKeys = require('snakecase-keys')

```
import snakecaseKeys from 'snakecase-keys'; //When invoked returns snakecaseKeys
import { snakecaseKeys } from 'snakecase-keys'; // Does not compile
import { snakeCaseKeys } from 'snakecase-keys';  // Does not compile
```
What am I doing wrong? 
Also, the namespace in the types definition is snakecaseKeys, but in your documentation you invoke the library as snakeCaseKeys() is that accidental?

Thanks in advance,

**Comment by bendrucker** [comment]
Hey—these typings were contributed and through I'm not an active TS user I think I see the issue and have addressed it.

When setting `export = fn`, you have to use `require`. In order to make this work like a typical TS import, I've changed it to `export default fn`. You'll need to tell TS to treat CommonJS modules like ES6 modules:

https://www.typescriptlang.org/tsconfig#esModuleInterop

I've also updated the readme case to match.

**Comment by alexmantaut** [comment]
It worked, thanks!

**Comment by naseemkullah** [comment]
Too late here but FWIW `import * as snakecaseKeys from 'snakecase-keys'`  would have worked.

**Comment by manuelnucci** [comment]
@naseemkullah are you sure about your answer? I cannot make it work.
