### ISSUE TITLE
Version 4.0.2 contains breaking chnages when comparedto 4.0.1

### ISSUE THREAD

**Issue by josnidhin** [bendrucker/snakecase-keys#52]
I just realized in `v4.0.2`, `to-snake-case` dependency was replaced with `snake-case`. The change looks innocent but those 2 modules has some subtle differences. Ideally changing dependencies should be considered breaking change and warrants a major version change.

As for the difference that I had mentioned see the sample code

```javascript
const snakeCase = require('to-snake-case');
console.log(snakeCase('accountId')); // account_id
console.log(snakeCase('accountID')); // account_i_d
```
vs
```javascript
const { snakeCase } = require('snake-case');
console.log(snakeCase('accountId')); // account_id
console.log(snakeCase('accountID')); // account_id
```

**Comment by bendrucker** [comment]
It would be breaking to publish 4.0.3 back with the old behavior now that 4.0.2 is out and has been out for a while. I believe this was reported before but it's too late to undo. I can deprecate 4.0.2 and publish a new major but that's about it.

**Comment by bendrucker** [comment]
> Ideally changing dependencies should be considered breaking change and warrants a major version change.

No, semver says otherwise. Breaking changes affect the interface of a package, not its implementation. The issue here is that it was unclear that the interface was changing. You can argue that it should have been apparent that this change was breaking—hindsight is 20/20. Semver is advisory, it does not solve for the fact that seemingly internal changes may cause interface breakage. There is no universal heuristic for what code changes result in breaking changes. 

End users should implement their own tests, semver doesn't prevent mistakes like this.

**Comment by bendrucker** [comment]
#47

**Comment by bendrucker** [comment]
```sh
npm deprecate snakecase-keys@4.0.2 'This version contains a breaking change for users depending on unspecified behaviors with repeated capital letters. See https://github.com/bendrucker/snakecase-keys/issues/47. Please upgrade to the identical 5.0.0 release instead.'
```

**Comment by josnidhin** [comment]
Thank you
